### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by Mencoreh** [IcyEndymion004/Slapper-Plus-Updated#1]
Can you explain in readme.md what your plugins bring? I know it is a plugin for slapper, but what does it do?

**Comment by IcyEndymion004** [comment]
Hi Slapper Plus Is a plugin that managers Slapper and Makes it alot easyer too use alot of the Slapper stuff is Managed in a UI

If You have More Questions DM me on discord at IcyEndymion004#3547 And Ill do my best to answer them

**Comment by IcyEndymion004** [comment]
And this has been added
